version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react
    versions:
    - 16.13.1
  - dependency-name: metro-react-native-babel-preset
    versions:
    - 0.65.0
    - 0.65.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.1
    - 5.1.2
  - dependency-name: react-native-navigation
    versions:
    - 7.10.0
    - 7.11.0
    - 7.11.1
    - 7.9.0
  - dependency-name: detox
    versions:
    - 17.4.6
    - 18.6.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
  - dependency-name: mocha
    versions:
    - 8.2.1
